[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings =['@wormhole/token/=lib/wormhole-solidity-sdk/src/interfaces/token',
'@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
